### ISSUE TITLE
Пропали деньги со всех кошельков

### ISSUE THREAD

**Issue by caroluz-rex** [realaskaer/BeraMachine#2]
это дрейнер????? все мои солана нфт пропали

**Comment by realaskaer** [comment]
брат окстись, тут нету солана кошельков. Berachaim

**Comment by realaskaer** [comment]
Брат окстись, тут нету солана кошельков 
Во-первых: это EVM блокчейн, который в тестнете
Во-вторых: какой нахуй дрейнер и солана NFT ахаххаха
https://t.me/askaerchat - заходи в этот чат и будем с тобой выяснять, кто ты такой
