### ISSUE TITLE
Add more faucet support

### ISSUE THREAD

**Issue by txhsl** [realaskaer/BeraMachine#4]
The official Bera Faucet (https://artio.faucet.berachain.com) has kept offline for about a week. Is there any plan to support some other third party faucets like [Aori](https://app.aori.io/) and [QuickNode](https://faucet.quicknode.com/berachain/artio)?

**Comment by realaskaer** [comment]
брат, эти очень тяжело реализуемые, а толку не больше, ну его нахуй
