### ISSUE TITLE
ERROR    | [Main 1] | BeraChain | Faucet | Unknown Error. Description: list index out of range | Try[21/21] Traceback (most recent call last):   File "C:\Users\accli\BeraMachine\utils\tools.py", line 143, in wrapper     return await func(self, *args, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by whatever193** [realaskaer/BeraMachine#7]
ERROR    | [Main 1] | BeraChain | Faucet | Unknown Error. Description: list index out of range | Try[21/21]
Traceback (most recent call last):
  File "C:\Users\accli\BeraMachine\utils\tools.py", line 143, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by realaskaer** [comment]
ты где-то обосрался с настройками
